In [1]:
import sys
sys.path.append('..')

import pandas as pd
from src import FounderAnalyzer

df = pd.read_csv("../data/feature_engineered_dataset.csv")

fa = FounderAnalyzer()

X, processed_df, feature_names, df_success_rate = fa.preprocessor.preprocess_data(df)

processed_df.head()

/Users/moncef/Documents/vela_mip/envs/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/Users/moncef/Documents/vela_mip/notebooks/../src/preprocessing.py:73: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column] = df[column].map(num_map).fillna(df[column])

Preprocessing data...
Original success rate: 9.1%
Dataset success rate: 1.9%
Selected 68 features

/Users/moncef/Documents/vela_mip/envs/lib/python3.12/site-packages/sklearn/impute/_base.py:598: UserWarning: Skipping features without any observed values: ['founder_uuid' 'name' 'org_name' 'persona']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(

,founder_uuid,name,org_name,education_level,education_institution,education_field_of_study,education_international_experience,education_publications_and_research,education_extracurricular_involvement,education_awards_and_honors,...,adaptability,emotional_intelligence,personal_branding,persona,founder_experience,acquisition_experience,acquirer_bigtech,ipo_experience,yoe,success
0,NaN,NaN,NaN,1.0,3.0,3.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,NaN,1.0,0.0,0.0,0.0,12.008219,1.0
2,NaN,NaN,NaN,3.0,1.0,3.0,0.0,1.0,0.0,0.0,...,2.0,0.0,1.0,NaN,2.0,NaN,0.0,0.0,38.586301,1.0
4,NaN,NaN,NaN,3.0,3.0,3.0,1.0,1.0,0.0,0.0,...,2.0,0.0,0.0,NaN,1.0,0.0,0.0,0.0,26.019178,1.0
5,NaN,NaN,NaN,2.0,3.0,2.0,1.0,0.0,0.0,0.0,...,2.0,0.0,0.0,NaN,1.0,0.0,0.0,0.0,17.293151,1.0
6,NaN,NaN,NaN,1.0,0.0,3.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,8.287671,1.0

In [2]:
main_cluster_labels, linkage_matrix = fa.main_clustering.create_main_clusters(X)

main_cluster_labels

Creating main clusters...

array([1, 1, 1, ..., 2, 5, 0])

In [5]:
results = fa.main_clustering.analyze_main_clusters(processed_df, main_cluster_labels, feature_names, df_success_rate)

results['important_features']

Analyzing main clusters...
0    [{'feature': 'yoe', 'shap_value': 0.67302763, ...
1    [{'feature': 'yoe', 'shap_value': 0.66549206, ...
2    [{'feature': 'education_institution', 'shap_va...
3    [{'feature': 'yoe', 'shap_value': 0.6026651, '...
4    [{'feature': 'number_of_leadership_roles', 'sh...
5    [{'feature': 'emotional_intelligence', 'shap_v...
6    [{'feature': 'nasdaq_leadership', 'shap_value'...
7    [{'feature': 'yoe', 'shap_value': 0.86342853, ...
Name: important_features, dtype: object